List<Map<String, String>> jokes = [
  {"title": "Why don’t skeletons fight each other?", "description": "They don’t have the guts."},
  {"title": "What do you call cheese that isn’t yours?", "description": "Nacho cheese!"},
  {"title": "Why couldn’t the bicycle stand up by itself?", "description": "It was two tired."},
  {"title": "What do you call a fake noodle?", "description": "An impasta."},
  {"title": "Why did the scarecrow win an award?", "description": "Because he was outstanding in his field."},
  {"title": "What’s orange and sounds like a parrot?", "description": "A carrot."},
  {"title": "Why don’t scientists trust atoms?", "description": "Because they make up everything!"},
  {"title": "How does a penguin build its house?", "description": "Igloos it together."},
  {"title": "What do you call a can opener that doesn’t work?", "description": "A can’t opener."},
  {"title": "Why did the math book look sad?", "description": "It had too many problems."},
  {"title": "Why couldn’t the leopard play hide and seek?", "description": "Because he was always spotted."},
  {"title": "What do you get when you cross a snowman and a dog?", "description": "Frostbite."},
  {"title": "What’s brown and sticky?", "description": "A stick."},
  {"title": "Why do seagulls fly over the ocean?", "description": "Because if they flew over the bay, they’d be bagels."},
  {"title": "Why did the golfer bring two pairs of pants?", "description": "In case he got a hole in one."},
  {"title": "What do you call a bear with no teeth?", "description": "A gummy bear."},
  {"title": "What kind of shoes do ninjas wear?", "description": "Sneakers."},
  {"title": "Why did the computer go to the doctor?", "description": "It caught a virus."},
  {"title": "How do you organize a space party?", "description": "You planet."},
  {"title": "Why was the broom late for work?", "description": "It swept in."},
];
